//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Deserialize, Serialize)]
#[sea_orm(table_name = "softwares")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub archive: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub version: String,
    pub version_major: i32,
    pub version_minor: i32,
    pub version_patch: i32,
    pub component: Option<String>,
    pub origin: Option<String>,
    pub label: Option<String>,
    pub architecture: Option<String>,
    pub download: Option<String>,
    pub others: Option<String>,
    pub flag: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation,Deserialize, Serialize)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
